# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
pod 'MagicalRecord'
pod 'AFNetworking', '2.6.0'
pod 'FastEasyMapping', '~> 1.0.1'
target 'Demo' do

end

